decimal.Decimal instead of float64
rwlist/autotrade-bot pull request #22
Opened 2020-07-28 17:28 UTC by RedClusive

Implementing https://github.com/shopspring/decimal for the sake of accuracy of calculations

2020-07-29 08:38 UTC, petuhovskiy requested changes

2020-07-29 08:38 UTC, petuhovskiy commented on pkg/formula/formula_basic.go
> +	return fmt.Sprintf("rate-%v+%v*(now-start)^%v", f.coef[0].String(), f.coef[1].String(), f.coef[2].String())
Можно использовать %s, он как раз вызывает .String() по умолчанию

2020-07-29 08:38 UTC, petuhovskiy commented on pkg/convert/convert.go
> +	dec, _ := decimal.NewFromString(str)
Ошибки не очень хорошо игнорировать. Понятно, что скорее всего в str действительно будет правильное число, но наверное лучше добавить хотя бы лог ошибки, если она произойдет, чтобы было видно в логах.

2020-07-29 08:38 UTC, petuhovskiy commented on pkg/draw/kline.go
> +	StartTime int64
Не очень очевидно что int64 это тип для времени. Есть два варианта:
- можно сделать свой тип, `type TradingTime int64` и использовать его
- можно везде перейти на time.Time

2020-07-29 08:38 UTC, petuhovskiy commented on pkg/formula/interface.go
> +	Calc(now float64) float64          // Возвращает значение в точке now
А зачем Calc который возвращает float64? Всегда же можно сделать CalcDec() и из него вытащить float64. 
Ну и в целом, от float64 можно отказаться почти везде.

2020-07-29 08:38 UTC, petuhovskiy commented on pkg/trade/binance/binance.go
> +			return convert.Sum(bal.Free, bal.Locked), nil
Может лучше сделать локальную функцию `sum(string, string)`, в этом пакете, а из convert удалить? Я не уверен что она (convert.Sum) понадобится где-то еще, кроме этой строчки.

2020-07-29 12:52 UTC, RedClusive commented on pkg/trade/binance/binance.go
> +			return convert.Sum(bal.Free, bal.Locked), nil
fixed

2020-07-29 12:52 UTC, RedClusive commented on pkg/formula/interface.go
> +	Calc(now float64) float64          // Возвращает значение в точке now
fixed

2020-07-29 12:52 UTC, RedClusive commented on pkg/draw/kline.go
> +	StartTime int64
fixed

2020-07-29 12:52 UTC, RedClusive commented on pkg/convert/convert.go
> +	dec, _ := decimal.NewFromString(str)
fixed

2020-07-29 12:52 UTC, RedClusive commented on pkg/formula/formula_basic.go
> +	return fmt.Sprintf("rate-%v+%v*(now-start)^%v", f.coef[0].String(), f.coef[1].String(), f.coef[2].String())
fixed

2020-07-31 12:25 UTC, petuhovskiy approved these changes

2020-07-31 12:25 UTC, petuhovskiy commented on pkg/convert/convert.go
> +		log.WithError(err).Error("in UnsafeDecimal")
Сюда можно добавить .WithField("str", str), чтобы в логах была та самая строка, которую не получилось спарсить в decimal

2020-07-31 12:44 UTC, RedClusive commented on pkg/convert/convert.go
> +		log.WithError(err).Error("in UnsafeDecimal")
fixed

2020-07-31 12:46 UTC, merged